data:
  home: data
  base: /base.json
  class: /class.json
  field_summary: /field/field.SUMMARY.pkl
  field_method: /field/field.METHOD.pkl
  raw_base_method: /raw/data.BASE_METHOD.json
  raw_base_summary: /raw/data.BASE_SUMMARY.json
  raw_class_method: /raw/data.CLASS_METHOD.json
  graph_dataset: data.base.pt

model:
  embed_size: 128
  hidden_size: 128
  weight_decay: 0.0001
  batch_size: 20
  max_code_len: 100
  max_com_len: 20
  max_node_num: 10
  gat_input_size: 256
  gat_hidden_size: 256
  gat_dropout: 0.1